### PR TITLE
fix response.setHeader

### PR DESCRIPTION
**Pull request by shinriyo**
fix response.setHeader

### CODE REVIEW

**Comment by kweinmeister** [comment]
Thanks for the contribution @shinriyo! Can you please submit a [CLA form](https://github.com/IBM-Swift/CLA) so we can review it?

**Comment by shinriyo** [comment]
@kweinmeister Thank you for replying.
I am going to submit.

**Comment by shinriyo** [comment]
@kweinmeister I sent email. Could you check it?

**Comment by kweinmeister** [comment]
@shinriyo Your CLA form was received, thank you!

Please cancel this pull request, and re-submit it against the `develop` branch, which has the latest code that is in progress. We appreciate your contribution!

**Comment by shinriyo** [comment]
@kweinmeister Thank you for receiving my CLA.
I checkout develop branch. However, `Sources/TodoList/Controllers/App.swift` source file was already removed or moved.

I built by `swift build`, now the error occurred, so I will try to do next pullrequest.
`error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/Kitura-net.git)`

**Comment by kweinmeister** [comment]
Hi @shinriyo, can you try cleaning your Packages and .build directories, and try swift build again?

rm -rf Packages
rm -rf .build

**Comment by shinriyo** [comment]
@kweinmeister I cleaned and build again but same error happened.

```
shinriyos-MacBook :: ~/kitura_apps/Kitura-TodoList ‹develop› % rm -rf Packages
shinriyos-MacBook :: ~/kitura_apps/Kitura-TodoList ‹develop› % rm -rf .build
shinriyos-MacBook :: ~/kitura_apps/Kitura-TodoList ‹develop› % swift build
Cloning https://github.com/IBM-Swift/todolist-couchdb.git
Resolved version: 0.0.1
Cloning https://github.com/IBM-Swift/todolist-api.git
Resolved version: 0.0.5
Cloning https://github.com/IBM-Swift/Kitura-CouchDB.git
Resolved version: 0.15.0
Cloning https://github.com/IBM-Swift/HeliumLogger.git
Resolved version: 0.7.4
Cloning https://github.com/IBM-Swift/LoggerAPI.git
Resolved version: 0.7.1
Cloning https://github.com/IBM-Swift/Kitura-net.git
Resolved version: 0.15.6
Cloning https://github.com/IBM-Swift/Kitura-sys.git
Resolved version: 0.13.2
Cloning https://github.com/IBM-Swift/BlueSocket.git
Resolved version: 0.5.18
Cloning https://github.com/IBM-Swift/CCurl.git
Resolved version: 0.1.1
Cloning https://github.com/IBM-Swift/CHttpParser.git
Resolved version: 0.1.1
Cloning https://github.com/IBM-Swift/SwiftyJSON.git
Resolved version: 7.0.3
Cloning https://github.com/IBM-Swift/Kitura.git
Resolved version: 0.13.8
error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/Kitura-net.git)
```

**Comment by dfirsht** [comment]
I fixed the dependencies on the develop branch. Please clean your Package directory and try again.

**Comment by shinriyo** [comment]
@dfirsht 
Thank you. I pulled new Package.swift
I tried clean and build, but dependencies was not fixed
```
~~~~
Resolved version: 0.15.6
error: The dependency graph could not be satisfied (https://github.com/IBM-Swift/Kitura-net.git)
```

**Comment by rfdickerson** [comment]
We have massively refactored Kitura-TodoList and App.swift has been removed. Let us know if you like the new changes!

**Pull request closed without merging**
