### PR TITLE
IBM-Swift/Kitura#504 Migrated TodoList to 05-31

### PR DESCRIPTION
**Pull request by NikitaSullivan**
Migrated to 05-31 swift snapshot

### CODE REVIEW

**Comment by rfdickerson** [comment]
Let's hold off on merging this until after the June demo. 

We will stick with 05-03 snapshot and 0.16 of Kitura. master branch contains the TodoList that matches the Todobackend spec, and develop branch will contain an example that contains user authentication.

**Comment by NikitaSullivan** [comment]
@rfdickerson that's completely fine and expected. Are you happy for the pull request to remain here in the meantime?

**Comment by rfdickerson** [comment]
Yep! We can keep that here.  I created a massive rewrite of TodoList where we can now plug in Cloudant or Redis as the backend that change is now in master, as of yesterday, btw.

**Comment by rfdickerson** [comment]
@NikitaSullivan can you resubmit this PR to develop instead of master?

**Comment by rfdickerson** [comment]
Invalidated, our new release will support 6-06 and Kitura 0.19

**Pull request closed without merging**
